name: MineCart-Detector
version: '${project.version}'
main: com.expectale.minecartdetector.MineCartDetector
api-version: 1.18
authors: [ smish ]
description: allows you to limit minecarts

commands:
  ml:
    permission: minecartdetector.use
    description: This command is used to limit the number of minecrats in a chunk

permissions:
  minecartdetector.use:
    description: Use MineCart-Detector plugin
    default: op
